### ISSUE TITLE
Python tutorial should handle failed start task

### ISSUE THREAD

**Issue by annatisch** [Azure-Samples/azure-batch-samples#200]
The Python article tutorial currently monitors tasks for completion - however does not monitor whether the nodes on the pool successfully start up - if start task fails then the tasks will never start leaving the script to poll for 20 minutes then exit without helpful feedback to the user.

**Comment by Frankygupta** [comment]
I am facing the same issue when I run the client script, the start task fails & it keeps polling. Also, why does the action fail?

**Comment by xingwu1** [comment]
New sample check the start task fail.
