### ISSUE TITLE
Know which user launched a Job

### ISSUE THREAD

**Issue by dedreira** [Azure-Samples/azure-batch-samples#249]
Hi all, is there a way to know which Active Directory user ran a job against an Azure Batch account authenticated with AAD?
I'm asking this with billing purposes on my mind :)
Thanks in advance!

**Comment by alfpark** [comment]
General questions about Batch should be asked here: https://github.com/Azure/Batch

You may be able to ascertain this information thorough AAD audit logs. Otherwise, you will need to track this information in your application.

Closing as this issue is not sample related.
