### ISSUE TITLE
Get started with Batch SDK for Node.js

### ISSUE THREAD

**Issue by robert-tinn** [Azure-Samples/azure-batch-samples#255]
I am trying to run nodjs_batch_client_samples.js but I get an error:

<An error occured while creating the pool...
nodejs_batch_client_sample.js:53
Object {body: "{>

I think the problem occurs when calling the add() method on batchClient.pool and this is because of the incorrect format of the poolConfig object. For example in the documentation the object has an attribute "targetDedicated" in the code, "targetDedicatedNodes" in the documentation (https://docs.microsoft.com/en-us/javascript/api/azure-batch/pooladdparameter?view=azure-node-latest#id) and "targetDedicatedComputeNodes" in a tutorial (https://docs.microsoft.com/en-us/azure/batch/batch-nodejs-get-started). However, I've tried all configurations but always get the same error.

I am using Node v8.12.0 on Windows 10.

**Comment by bgklein** [comment]
The correct attribute for the current SDK version is targetDedicatedNodes.  Could you try re-trying the operation with attributes as specified by this model https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/batch/lib/models/poolAddParameter.js ?

If you continue to get the error please post the full error contents.

**Comment by bgklein** [comment]
Due to no response closing issue. Feel free to reopen if the issue recurrs

**Comment by alfpark** [comment]
Closing as there has been no response. Please re-open if you continue to encounter errors.
